//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary1.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access method.
        /// </summary>
        public static string accessmethod {
            get {
                return ResourceManager.GetString("accessmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altname.
        /// </summary>
        public static string altname {
            get {
                return ResourceManager.GetString("altname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string areyousure {
            get {
                return ResourceManager.GetString("areyousure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team.
        /// </summary>
        public static string awayteam {
            get {
                return ResourceManager.GetString("awayteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string captain {
            get {
                return ResourceManager.GetString("captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        public static string datasource {
            get {
                return ResourceManager.GetString("datasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string display {
            get {
                return ResourceManager.GetString("display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string draws {
            get {
                return ResourceManager.GetString("draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string exitapplication {
            get {
                return ResourceManager.GetString("exitapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string favorite {
            get {
                return ResourceManager.GetString("favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code.
        /// </summary>
        public static string fifacode {
            get {
                return ResourceManager.GetString("fifacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        public static string gamesplayed {
            get {
                return ResourceManager.GetString("gamesplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string goals {
            get {
                return ResourceManager.GetString("goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Against.
        /// </summary>
        public static string goalsagainst {
            get {
                return ResourceManager.GetString("goalsagainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Differential.
        /// </summary>
        public static string goalsdifferential {
            get {
                return ResourceManager.GetString("goalsdifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals For.
        /// </summary>
        public static string goalsfor {
            get {
                return ResourceManager.GetString("goalsfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID.
        /// </summary>
        public static string groupid {
            get {
                return ResourceManager.GetString("groupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Letter.
        /// </summary>
        public static string groupletter {
            get {
                return ResourceManager.GetString("groupletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string hometeam {
            get {
                return ResourceManager.GetString("hometeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string losses {
            get {
                return ResourceManager.GetString("losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string match {
            get {
                return ResourceManager.GetString("match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string matches {
            get {
                return ResourceManager.GetString("matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match list.
        /// </summary>
        public static string matchlist {
            get {
                return ResourceManager.GetString("matchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 3 favorites!.
        /// </summary>
        public static string maxthreefavorites {
            get {
                return ResourceManager.GetString("maxthreefavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 3 selections!.
        /// </summary>
        public static string maxthreeselections {
            get {
                return ResourceManager.GetString("maxthreeselections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string method {
            get {
                return ResourceManager.GetString("method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of goals.
        /// </summary>
        public static string numberofgoals {
            get {
                return ResourceManager.GetString("numberofgoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of yellow cards.
        /// </summary>
        public static string numberofyellowcards {
            get {
                return ResourceManager.GetString("numberofyellowcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string opensettings {
            get {
                return ResourceManager.GetString("opensettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page setup.
        /// </summary>
        public static string pagesetup {
            get {
                return ResourceManager.GetString("pagesetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        public static string printpreview {
            get {
                return ResourceManager.GetString("printpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string ranking {
            get {
                return ResourceManager.GetString("ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking list.
        /// </summary>
        public static string rankinglist {
            get {
                return ResourceManager.GetString("rankinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set initial settings.
        /// </summary>
        public static string setinitialsettings {
            get {
                return ResourceManager.GetString("setinitialsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitutions.
        /// </summary>
        public static string substitutions {
            get {
                return ResourceManager.GetString("substitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string visitors {
            get {
                return ResourceManager.GetString("visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors list.
        /// </summary>
        public static string visitorslist {
            get {
                return ResourceManager.GetString("visitorslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string wins {
            get {
                return ResourceManager.GetString("wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string yellowcards {
            get {
                return ResourceManager.GetString("yellowcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
